services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=999
      - PGID=995
      - TZ=America/New_York
      - JELLYFIN_PublishedServerUrl=tharmas.local
    volumes:
      - /etc/jellyfin/config:/config
      - /media/colemine/tv:/data/tvshows
      - /media/colemine/movies:/data/movies
      - /media/colemine/music:/data/music
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    networks:
      - medianet
    restart: unless-stopped
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    ports:
      - "8080:8080"
    volumes:
      - "/var/sabnzbd:/config"
      - "/media/colemine/downloads/complete:/downloads"
      - "/media/colemine/downloads/incomplete:/incomplete-downloads"
    environment:
      TZ: America/New_York
      PUID: 999
      PGID: 995
    networks:
      - medianet
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - "8989:8989"
    volumes:
      - "/etc/sonarr:/config"
      - "/media/colemine/downloads/complete:/downloads"
      - "/media/colemine/tv:/tv"
    environment:
      TZ: America/New_York
      PUID: 999
      PGID: 995
    networks:
      - medianet
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    ports:
      - "7878:7878"
    volumes:
      - "/etc/radarr:/config"
      - "/media/colemine/downloads/complete:/downloads"
      - "/media/colemine/movies:/movies"
    environment:
      TZ: America/New_York
      PUID: 999
      PGID: 995
    networks:
      - medianet
    restart: unless-stopped
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    ports:
      - "8686:8686"
    volumes:
      - "/etc/lidarr:/config"
      - "/media/colemine/downloads/complete:/downloads"
      - "/media/colemine/music:/music"
    environment:
      TZ: America/New_York
      PUID: 999
      PGID: 995
    networks:
      - medianet
    restart: unless-stopped
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    ports:
      - "3579:3579"
    volumes:
      - "/etc/ombi:/config"
    environment:
      TZ: America/New_York
      PUID: 999
      PGID: 995
    networks:
      - medianet
    restart: unless-stopped
networks:
  medianet:
    name: medianet
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24